### ISSUE TITLE
What does ARM-L/ARM-M/ARM-S mean?

### ISSUE THREAD

**Issue by wangqiim** [chenbong/ARM-Net#1]
It is a interesting work. I have some questions about your paper.
1. In your work. When inference, my understanding is to build edge table at first, then use this table when inference. But How to decide which width network a patch choose? The others methods in Figure 7 is clear. But I can't know how `ARM-FSRCNN` choose width. It is confuse me (
2. In Table 1&2,  ARM-L/ARM-M/ARM-S means: fixed width no matter what the input patch is, right?
3. About ARM-L/ARM-M/ARM-S,  If just fix width. May be you should compare with ClassSR use your width choose policy insted of  fixing width?
4. By the way. In table 1 (row: Module FSRCNN, column: FLOPS) is 0%, may be error. :)

Many questions from me. Thanks!

**Comment by chenbong** [comment]
Thank you for your interest in our work.
1. When inference, the subnet selected for each patch is calculated according to Equation 5. The specific selection process can refer to Figure 8 in the Appendix.
2. The ARM-L/M/S in Tables 1&2 indicates that the computational overhead of the network is adjusted by using different hyperparameters $\eta$ in Eq. 5.
3. ARM-L/M/S is not a fixed width, but automatically selects the subnet with different width according to the edge score of the patch according to Eq. 5.
4. The 0% in Table 1 is an error, and will be modified in a later version.

If you have other questions, feel free to open the issue to discuss.

**Comment by wangqiim** [comment]
Make sense, Thank you!

**Comment by yuwei66** [comment]
请问ARM-L/ARM-M/ARM-S在FSRCNN,CARN,SRResnet 分别对应的eta值是多少?  如何设置参数得出论文表2的结果.
